### ISSUE TITLE
Add funding.yml

### ISSUE THREAD

**Issue by Caaz** [Caaz/tableturner#4]
[Gotta shill somehow](https://opencollective.com/tilde-dev)

**Comment by joanjeremiah** [comment]
I would like to solve this issue .Kindly assign this task to me

**Comment by Caaz** [comment]
Sorry bout that @joanjeremiah saw the PR before I saw your comment, due to the webhooks I've got setup for this repo.

**Comment by joanjeremiah** [comment]
> Sorry bout that @joanjeremiah saw the PR before I saw your comment, due to the webhooks I've got setup for this repo.

No problem
